"""create profile users

Revision ID: 0925e7f66511
Revises: 9cf4ddaa5c4a
Create Date: 2023-10-17 22:34:26.769611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0925e7f66511'
down_revision: Union[str, None] = '9cf4ddaa5c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.Enum('admin', 'student', 'professor', 'research', 'basic', name='userprofile'), nullable=False, server_default=str('basic')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
